name: anacin-x
channels:
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - anaconda=2019.07
  - anaconda-client=1.7.2
  - anaconda-project=0.8.3
  - asn1crypto=0.24.0
  - astroid=2.2.5
  - astropy=3.0.5
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - babel=2.7.0
  - backcall=0.1.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.os=0.1.1
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.7.1
  - bitarray=0.9.3
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.1.0
  - blosc=1.16.3
  - bokeh=1.2.0
  - boto=2.49.0
  - bottleneck=1.2.1
  - bzip2=1.0.8
  - ca-certificates=2019.5.15
  - cairo=1.14.12
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=1.2.1
  - clyent=1.2.2
  - colorama=0.4.1
  - conda=4.8.1
  - conda-build=3.18.8
  - conda-env=2.6.0
  - conda-package-handling=1.6.0
  - conda-verify=3.4.2
  - contextlib2=0.5.5
  - cryptography=2.7
  - curl=7.65.2
  - cycler=0.10.0
  - cython=0.29.12
  - cytoolz=0.10.0
  - dask=2.1.0
  - dask-core=2.1.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - distributed=2.1.0
  - docutils=0.14
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.6
  - fastcache=1.1.0
  - filelock=3.0.12
  - flask=1.1.1
  - fontconfig=2.13.0
  - freetype=2.9.1
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gevent=1.4.0
  - glib=2.56.2
  - glob2=0.7
  - gmp=6.1.2
  - gmpy2=2.0.8
  - greenlet=0.4.15
  - h5py=2.8.0
  - hdf5=1.10.2
  - heapdict=1.0.0
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.8
  - imageio=2.5.0
  - imagesize=1.1.0
  - importlib_metadata=0.17
  - ipykernel=5.1.1
  - ipython=7.6.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.0
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - jupyterlab=1.2.4
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - lazy-object-proxy=1.4.1
  - libarchive=3.3.3
  - libcurl=7.65.2
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libopenblas=0.2.20
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.33
  - locket=0.2.0
  - lxml=4.3.4
  - lz4-c=1.8.1.2
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mccabe=0.6.1
  - mistune=0.8.4
  - more-itertools=7.0.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpi=1.0
  - mpi4py=3.0.3
  - mpich=3.3.2
  - mpmath=1.1.0
  - msgpack-python=0.6.1
  - multipledispatch=0.6.0
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.3
  - nltk=3.4.4
  - nose=1.3.7
  - notebook=6.0.0
  - numexpr=2.6.7
  - numpy=1.14.5
  - numpy-base=1.14.5
  - numpydoc=0.9.1
  - olefile=0.46
  - openblas=0.2.20
  - openblas-devel=0.2.20
  - openpyxl=2.6.2
  - openssl=1.1.1c
  - packaging=19.0
  - pandas=0.23.4
  - pandoc=2.0.0.1
  - pandocfilters=1.4.2
  - parso=0.5.0
  - partd=1.0.0
  - patchelf=0.9
  - path.py=12.0.1
  - pathlib2=2.3.4
  - patsy=0.5.1
  - pcre=8.43
  - pep8=1.7.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.1.1
  - pixman=0.34.0
  - pkginfo=1.5.0.1
  - pluggy=0.12.0
  - ply=3.11
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - psutil=5.6.3
  - ptyprocess=0.6.0
  - py=1.8.0
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pycrypto=2.6.1
  - pycurl=7.43.0.3
  - pyflakes=2.1.1
  - pygments=2.4.2
  - pylint=2.3.1
  - pyodbc=4.0.26
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyrsistent=0.14.11
  - pysocks=1.7.0
  - pytables=3.4.4
  - pytest=5.0.1
  - pytest-arraydiff=0.3
  - pytest-astropy=0.5.0
  - pytest-doctestplus=0.3.0
  - pytest-openfiles=0.3.1
  - pytest-remotedata=0.3.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - python-libarchive-c=2.8
  - pytz=2019.1
  - pywavelets=1.0.3
  - pyyaml=5.1.1
  - pyzmq=18.0.0
  - readline=7.0
  - requests=2.22.0
  - ruamel_yaml=0.15.46
  - scikit-image=0.15.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - six=1.12.0
  - snappy=1.1.7
  - snowballstemmer=1.9.0
  - sortedcollections=1.1.2
  - sortedcontainers=2.1.0
  - soupsieve=1.8
  - sphinx=2.1.2
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sphinxcontrib-websupport=1.1.2
  - sqlalchemy=1.3.5
  - sqlite=3.29.0
  - statsmodels=0.10.0
  - sympy=1.4
  - tblib=1.4.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.32.1
  - traitlets=4.3.2
  - unicodecsv=0.14.1
  - unixodbc=2.3.7
  - urllib3=1.24.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.4
  - wheel=0.33.4
  - widgetsnbextension=3.5.0
  - wrapt=1.11.2
  - xlrd=1.2.0
  - xlsxwriter=1.1.8
  - xlwt=1.3.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=1.0.0
  - zipp=0.5.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - bottle==0.12.18
    - conan==1.21.0
    - deprecation==2.0.7
    - distro==1.1.0
    - docopt==0.6.2
    - fasteners==0.15
    - grip==4.5.2
    - markdown==3.1.1
    - monotonic==1.5
    - node-semver==0.6.1
    - patch-ng==1.17.2
    - path-and-address==2.0.1
    - pluginbase==0.7
    - pyjwt==1.7.1
